    <!-- navigation bar -->
<nav>
    <ul class="nav__link--list">
        <li class="nav__link">
        <a href="index.php" class="nav__link--anchor link__hover-effect link__hover-effect--white
        ">Index</a>
        </li>
        <li class="nav__link">
        <a href="topic.php" class="nav__link--anchor link__hover-effect link__hover-effect--white
        ">Topic</a>
        </li>
        <li class="nav__link">
        <a href="quiz.php" class="nav__link--anchor link__hover-effect link__hover-effect--white
        ">Quiz</a>
        </li>
        <li class="nav__link">
        <a href="enhancements.php" class="nav__link--anchor link__hover-effect link__hover-effect--white
        ">Enhancements</a>
        </li>
        <li class="nav__link">
        <a href="phpenhancements.php" class="nav__link--anchor link__hover-effect link__hover-effect--white
        ">PHP Enhancements</a>
        </li>
        <li class="nav__link">
        <a href="login.php" class="nav__link--anchor link__hover-effect link__hover-effect--white
        ">Admin Login</a>
        </li>
    </ul>
</nav>